apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-iot-app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: iot-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
